version: '3'

services:
  db:
    image: redis

  web:
    image: michaelpak/secretsanta
    volumes:
      - ./resources/users.yml:/usr/src/resources/users.yml
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - REDIS_HOST=db