version: '3'
services:
  db:
    image: redis
    container_name: secretsanta-db
  web:
    image: michaelpak/secretsanta
    volumes:
    - /root/users.yml:/usr/src/resources/users.yml
    ports:
    - "8000:8000"
    depends_on:
    - db
    environment:
    - REDIS_HOST=db
    container_name: secretsanta-web
  watchtower:
    image: v2tec/watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: -i 10 --cleanup
    container_name: watchtower