version: 2
jobs:
  build:
    working_directory: /app
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install dependencies
        command: |
          apk add --no-cache \
            py-pip=9.0.0-r1
          pip install \
            docker-compose==1.12.0 \
            awscli==1.11.76
    - restore_cache:
        keys:
        - v1-{{ .Branch }}
        paths:
        - /caches/app.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/app.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=app -t michaelpak/secretsanta .
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches
          docker save -o /caches/app.tar michaelpak/secretsanta
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
        - /caches/app.tar
    - run:
        name: Push application Docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push michaelpak/secretsanta
  deploy:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - add_ssh_keys:
        fingerprints:
        - "ef:22:2e:5f:3b:f4:1d:97:72:3d:03:f7:9c:d6:34:06"
    - deploy:
        name: Deploy applicaion
        command: ssh -o StrictHostKeyChecking=no -v root@$DROPLET_IP "docker pull michaelpak/secretsanta; docker-compose stop web; docker-compose rm -f web; docker-compose up -d"

workflows:
  version: 2
  ci/cd:
    jobs:
    - build
    - deploy:
        requires:
        - build