---
- hosts: all

  vars:
  - docker_install_compose: true
  - docker_install_compose: false

  - caddy_systemd_capabilities_enabled: True
  - caddy_config: |
      secretsanta.pak.digital {
        log /var/log/caddy/access.log
        errors /var/log/caddy/error.log
        proxy / 127.0.0.1:8000 {
          transparent
        }
        tls mialpak@gmail.com
      }

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  roles:
  - geerlingguy.docker
  - antoiner77.caddy

  tasks:
  - name: Install pip3
    apt:
      name: python3-pip

  - name: Install docker-compose
    pip:
      name: docker-compose

  - name: Copy users list
    copy:
      src: ../resources/users.yml
      dest: /root/users.yml

  - name: Copy docker compose config
    copy:
      src: ../docker-compose.yml
      dest: /root/docker-compose.yml

  - name: Start applications
    docker_service:
      project_src: /root
      state: present